# Generated by Django 4.2.7 on 2023-11-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reflectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.IntegerField()),
                ('content', models.TextField()),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.entryaudio')),
                ('reflector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflectors.reflector')),
            ],
        ),
    ]
