# Generated by Django 4.2.7 on 2023-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='magnitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='sentiment',
            field=models.FloatField(),
        ),
    ]
